[theme]
# Primary accent color for interactive elements.
primaryColor = "#d33682"

# Background color for the main content area.
backgroundColor = "#7f8272"

# Background color used for the sidebar and most interactive widgets.
secondaryBackgroundColor = "#3a3b37"

# Color used for almost all text.
textColor = "#fff"