[theme]
# Primary accent color for interactive elements.
primaryColor = "#d33682"

# Background color for the main content area.
backgroundColor = "#021526"

# Background color used for the sidebar and most interactive widgets.
secondaryBackgroundColor = "#101112"

# Color used for almost all text.
textColor = "#fff"

[server]
headless = true
